# Zip specified folder to release. (BattStudio)
# When manually triggered, draft release will be created.

name: Create Release

on:
  # Trigger on push to tags
  push:
    tags:
      - "v*" # Trigger on pushes to tags matching v*, i.e., v1.0, v20.15.10
  # Trigger for manual dispatch
  workflow_dispatch: # Enables manual triggering of the workflow


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Zip the specified folder
      - name: Create ZIP File
        run: |
          zip -r "simulate_p2d_plus FMU v1.4.zip" testrpo

      # # Step 2.5: Determine Draft Status
      # - name: Determine Draft Status
      #   id: draft_status
      #   run: |
      #     if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
      #       echo "draft=true" >> $GITHUB_ENV
      #     else
      #       echo "draft=false" >> $GITHUB_ENV
      #     fi

      # Step 3: Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false

        # with:
        #   tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        #   release_name: Release ${{ github.event.inputs.tag_name || github.ref_name }}
        #   draft: ${{ env.draft }}
        #   prerelease: false         

      # Step 4: Upload the ZIP file as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "simulate_p2d_plus FMU v1.4.zip"
          asset_name: "simulate_p2d_plus FMU v1.4.zip"
          asset_content_type: application/zip
