name: Create Release

on:
  push:
    tags:
      - "v*" # Trigger on pushes to tags matching v*, i.e., v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Zip the 'testrpo' folder
      - name: Create ZIP File
        run: |
          zip -r "simulate_p2d_plus FMU v1.4.zip" testrpo

      # Step 3: Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: true

      # Step 4: Upload the ZIP file as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "simulate_p2d_plus FMU v1.4.zip"
          asset_name: "simulate_p2d_plus FMU v1.4.zip"
          asset_content_type: application/zip
